import { DungeonMapDefinition } from '../types';

export const ANNOYED_ANIMALS_MAP: DungeonMapDefinition = {
  id: 'annoyed-animals',
  name: 'Annoyed Animals',
  difficulty: 'Novice',
  startCellIds: [
    'start-2-tl', 'start-9-tl', 'start-6-tl', 'start-7-tl', 'start-3-fl', 'start-12-fl',
    'start-4-tr', 'start-5-tr', 'start-8-tr', 'start-10-tr', 'start-11-tr',
  ],
  cells: {
    // ==========================================
    // ZONE 1: TOP-LEFT REGION
    // ==========================================
    'start-2-tl': { id: 'start-2-tl', type: 'START', label: '2', value: 2, row: 0, col: 2, x: 18.0, y: 7.0, connectedCellIds: ['start-9-tl', 'activate-4-tl'] },
    'start-9-tl': { id: 'start-9-tl', type: 'START', label: '9', value: 9, row: 1, col: 2, x: 18.0, y: 15.0, connectedCellIds: ['start-2-tl', 'start-6-tl', 'activate-4-tl'] },
    'activate-4-tl': { id: 'activate-4-tl', type: 'GRAY_ACTIVATION', label: '4 (Star)', value: 4, requiresEqualDice: true, row: 0, col: 3, x: 26.0, y: 11.0, connectedCellIds: ['start-2-tl', 'start-9-tl', 'monster-purple-pup'] },

    'start-6-tl': { id: 'start-6-tl', type: 'START', label: '6', value: 6, row: 2, col: 2, x: 18.0, y: 23.0, connectedCellIds: ['start-9-tl', 'start-7-tl', 'white-pairs-tl', 'activate-10-tl'] },
    'activate-10-tl': { id: 'activate-10-tl', type: 'GRAY_ACTIVATION', label: '10 (Star)', value: 10, row: 2, col: 3, x: 26.0, y: 27.0, connectedCellIds: ['start-6-tl', 'start-7-tl', 'white-pairs-tl', 'monster-grey-hound'] },
    'white-pairs-tl': { id: 'white-pairs-tl', type: 'REGULAR', label: 'Pairs', requiresEqualDice: true, row: 2, col: 3.5, x: 29.5, y: 25.0, connectedCellIds: ['start-6-tl', 'activate-10-tl', 'white-7-top'] },

    'start-7-tl': { id: 'start-7-tl', type: 'START', label: '7', value: 7, row: 3, col: 2, x: 18.0, y: 31.0, connectedCellIds: ['start-6-tl', 'start-3-fl', 'activate-10-tl'] },
    'start-3-fl': { id: 'start-3-fl', type: 'START', label: '3', value: 3, row: 3, col: 1, x: 11.0, y: 31.0, connectedCellIds: ['start-7-tl', 'start-12-fl', 'activate-6-fl'] },
    'start-12-fl': { id: 'start-12-fl', type: 'START', label: '12', value: 12, row: 3, col: 0, x: 4.0, y: 31.0, connectedCellIds: ['start-3-fl', 'white-5-fl'] },
    'white-5-fl': { id: 'white-5-fl', type: 'REGULAR', label: '5', value: 5, row: 4, col: 0, x: 4.0, y: 41.0, connectedCellIds: ['start-12-fl', 'activate-6-fl', 'activate-4-fl'] },
    'activate-4-fl': { id: 'activate-4-fl', type: 'GRAY_ACTIVATION', label: '4 (Star)', value: 4, row: 5, col: 1, x: 5.5, y: 51.0, connectedCellIds: ['white-5-fl', 'white-12-bl', 'monster-grey-hound'] },
    'activate-6-fl': { id: 'activate-6-fl', type: 'GRAY_ACTIVATION', label: '6 (Star)', value: 6, row: 4, col: 1, x: 11.0, y: 41.0, connectedCellIds: ['start-3-fl', 'white-5-fl', 'monster-grey-hound'] },

    'white-7-top': { id: 'white-7-top', type: 'REGULAR', label: '7', value: 7, row: 2, col: 4, x: 32.5, y: 23.5, connectedCellIds: ['white-pairs-tl', 'monster-purple-pup'] },
    'monster-purple-pup': {
      id: 'monster-purple-pup',
      type: 'MONSTER',
      label: 'Purple Pup',
      monsterId: 'purple-pup',
      row: 1,
      col: 5,
      x: 35.5,
      y: 14.5,
      connectedCellIds: ['activate-4-tl', 'white-7-top', 'activate-3-top', 'white-10-fist-top'],
      monsterLifeBoxes: [
        { cellId: 'm-purple-3', value: 3 },
        { cellId: 'm-purple-4', value: 4 },
        { cellId: 'm-purple-11', value: 11, requiresActivationCellId: 'activate-10-tl' },
      ],
    },
    'white-10-fist-top': { id: 'white-10-fist-top', type: 'REGULAR', label: '10 (Fist ✊)', value: 10, requiresEqualDice: true, row: 0, col: 6, x: 45.5, y: 7.0, connectedCellIds: ['monster-purple-pup', 'white-12-uc1'] },

    // ==========================================
    // ZONE 2: TOP-RIGHT REGION
    // ==========================================
    'start-4-tr': { id: 'start-4-tr', type: 'START', label: '4', value: 4, row: 0, col: 11, x: 74.0, y: 10.5, connectedCellIds: ['activate-3-tr', 'start-5-tr'] },
    'activate-3-tr': { id: 'activate-3-tr', type: 'GRAY_ACTIVATION', label: '3 (Star)', value: 3, row: 0, col: 10, x: 67.0, y: 10.5, connectedCellIds: ['start-4-tr', 'monster-green-growler'] },
    'start-5-tr': { id: 'start-5-tr', type: 'START', label: '5', value: 5, row: 1, col: 11, x: 76.0, y: 18.0, connectedCellIds: ['start-4-tr', 'start-8-tr', 'activate-9-tr'] },
    'activate-9-tr': { id: 'activate-9-tr', type: 'GRAY_ACTIVATION', label: '9 (Star)', value: 9, row: 2, col: 10, x: 70.0, y: 24.5, connectedCellIds: ['start-5-tr', 'start-8-tr', 'monster-green-growler'] },
    'start-8-tr': { id: 'start-8-tr', type: 'START', label: '8', value: 8, row: 2, col: 11, x: 76.5, y: 26.0, connectedCellIds: ['start-5-tr', 'start-10-tr', 'activate-9-tr'] },
    'start-10-tr': { id: 'start-10-tr', type: 'START', label: '10', value: 10, row: 3, col: 11, x: 76.0, y: 34.0, connectedCellIds: ['start-8-tr', 'start-11-tr', 'white-2-gem-tr'] },
    'start-11-tr': { id: 'start-11-tr', type: 'START', label: '11', value: 11, row: 4, col: 11, x: 77.5, y: 42.0, connectedCellIds: ['start-10-tr', 'white-2-gem-tr', 'white-gem-12-tr'] },
    'white-gem-12-tr': { id: 'white-gem-12-tr', type: 'REGULAR', label: '12 (Gem)', value: 12, row: 5, col: 11, x: 84.0, y: 48.0, connectedCellIds: ['start-11-tr', 'chest-3', 'white-pairs-tr'] },
    'white-pairs-tr': { id: 'white-pairs-tr', type: 'REGULAR', label: 'Pairs', requiresEqualDice: true, row: 4, col: 10, x: 73.0, y: 42.0, connectedCellIds: ['white-gem-12-tr', 'white-7-tr'] },
    'white-2-gem-tr': { id: 'white-2-gem-tr', type: 'REGULAR', label: '2 (Gem)', value: 2, requiresEqualDice: true, row: 3, col: 10, x: 70.5, y: 34.0, connectedCellIds: ['start-10-tr', 'start-11-tr', 'white-7-tr'] },
    'white-7-tr': { id: 'white-7-tr', type: 'REGULAR', label: '7', value: 7, row: 3, col: 9.5, x: 65.5, y: 34.5, connectedCellIds: ['white-2-gem-tr', 'white-pairs-tr', 'monster-green-growler'] },
    'monster-green-growler': {
      id: 'monster-green-growler',
      type: 'MONSTER',
      label: 'Green Growler',
      monsterId: 'green-growler',
      row: 2,
      col: 10,
      x: 64.5,
      y: 22.5,
      connectedCellIds: ['activate-3-tr', 'activate-9-tr', 'white-7-tr'],
      monsterLifeBoxes: [
        { cellId: 'm-growler-3', value: 3 },
        { cellId: 'm-growler-5', value: 5 },
        { cellId: 'm-growler-9', value: 9, requiresActivationCellId: 'activate-9-tr' },
      ],
    },

    // ==========================================
    // ZONE 3: MIDDLE / CENTER REGION
    // ==========================================
    'monster-grey-hound': {
      id: 'monster-grey-hound',
      type: 'MONSTER',
      label: 'Grey Hound',
      monsterId: 'grey-hound',
      row: 5,
      col: 3,
      x: 23.0,
      y: 43.0,
      connectedCellIds: ['activate-10-tl', 'activate-6-fl', 'activate-4-fl', 'white-5-bl', 'white-9-mid'],
      monsterLifeBoxes: [
        { cellId: 'm-grey-6', value: 6 },
        { cellId: 'm-grey-8', value: 8 },
        { cellId: 'm-grey-10', value: 10, requiresActivationCellId: 'activate-10-tl' },
      ],
    },
    'white-9-mid': { id: 'white-9-mid', type: 'REGULAR', label: '9', value: 9, row: 3, col: 4, x: 34.0, y: 36.0, connectedCellIds: ['monster-grey-hound', 'chest-11', 'white-pairs-mid'] },
    'white-pairs-mid': { id: 'white-pairs-mid', type: 'REGULAR', label: 'Pairs', requiresEqualDice: true, row: 3, col: 4.5, x: 36.0, y: 34.0, connectedCellIds: ['white-9-mid', 'chest-11', 'white-10-mid'] },
    'chest-11': { id: 'chest-11', type: 'CHEST', label: 'Chest 11 (+1 Torch)', row: 3, col: 5, x: 38.5, y: 32.0, connectedCellIds: ['white-9-mid', 'white-pairs-mid', 'white-12-gem-mid'], chestReward: 'TORCH' },
    'white-12-gem-mid': { id: 'white-12-gem-mid', type: 'REGULAR', label: '12 (Gem)', value: 12, row: 3, col: 6, x: 43.0, y: 37.5, connectedCellIds: ['chest-11', 'activate-3-boss'] },
    'activate-3-boss': { id: 'activate-3-boss', type: 'GRAY_ACTIVATION', label: '3 (Star)', value: 3, row: 3, col: 7, x: 49.5, y: 38.5, connectedCellIds: ['white-12-gem-mid', 'monster-boss-bearpion', 'white-9-center'] },
    'activate-3-top': { id: 'activate-3-top', type: 'GRAY_ACTIVATION', label: '3 (Star)', value: 3, row: 2, col: 5, x: 39.5, y: 23.5, connectedCellIds: ['monster-purple-pup', 'white-10-mid'] },
    'white-10-mid': { id: 'white-10-mid', type: 'REGULAR', label: '10', value: 10, row: 2, col: 6, x: 45.0, y: 26.0, connectedCellIds: ['activate-3-top', 'white-pairs-mid', 'white-12-uc1'] },
    'white-12-uc1': { id: 'white-12-uc1', type: 'REGULAR', label: '12 (Gem)', value: 12, row: 1, col: 6, x: 47.5, y: 15.0, connectedCellIds: ['white-10-fist-top', 'white-10-mid', 'white-12-uc2'] },
    'white-12-uc2': { id: 'white-12-uc2', type: 'REGULAR', label: '12 (Gem)', value: 12, row: 1, col: 7, x: 52.0, y: 15.0, connectedCellIds: ['white-12-uc1', 'white-9-center'] },
    'white-9-center': { id: 'white-9-center', type: 'REGULAR', label: '9', value: 9, row: 2, col: 7, x: 53.0, y: 30.0, connectedCellIds: ['white-12-uc2', 'activate-3-boss', 'white-6-center'] },
    'white-6-center': { id: 'white-6-center', type: 'REGULAR', label: '6', value: 6, row: 2, col: 8, x: 60.0, y: 30.0, connectedCellIds: ['white-9-center', 'white-pairs-center'] },
    'white-pairs-center': { id: 'white-pairs-center', type: 'REGULAR', label: 'Pairs', requiresEqualDice: true, row: 2, col: 8.5, x: 62.0, y: 32.0, connectedCellIds: ['white-6-center', 'white-7-tr', 'white-11-fist-center'] },
    'white-11-fist-center': { id: 'white-11-fist-center', type: 'REGULAR', label: '11 (Fist ✊)', value: 11, row: 3, col: 8, x: 63.5, y: 38.5, connectedCellIds: ['white-pairs-center', 'activate-8-boss'] },
    'activate-8-boss': { id: 'activate-8-boss', type: 'GRAY_ACTIVATION', label: '8 (Star)', value: 8, row: 4, col: 8, x: 61.0, y: 43.5, connectedCellIds: ['white-11-fist-center', 'monster-boss-bearpion'] },
    'white-10-boss-left': { id: 'white-10-boss-left', type: 'REGULAR', label: '10', value: 10, row: 4, col: 6, x: 42.0, y: 48.5, connectedCellIds: ['white-5-boss-left'] },
    'white-5-boss-left': { id: 'white-5-boss-left', type: 'REGULAR', label: '5', value: 5, row: 5, col: 6, x: 46.0, y: 57.0, connectedCellIds: ['white-10-boss-left', 'white-7-bm-low'] },
    'monster-boss-bearpion': {
      id: 'monster-boss-bearpion',
      type: 'MONSTER',
      label: 'Beefy Bearpion',
      monsterId: 'boss-bearpion',
      row: 5,
      col: 7,
      x: 58.0,
      y: 50.0,
      connectedCellIds: ['activate-3-boss', 'activate-8-boss'],
      monsterLifeBoxes: [
        { cellId: 'm-boss-3', value: 3 },
        { cellId: 'm-boss-4', value: 4 },
        { cellId: 'm-boss-5', value: 5 },
        { cellId: 'm-boss-8', value: 8 },
        { cellId: 'm-boss-11a', value: 11 },
        { cellId: 'm-boss-11b', value: 11, requiresActivationCellId: 'activate-8-boss' },
      ],
    },

    // ==========================================
    // ZONE 4 & 5: BOTTOM-LEFT & BOTTOM-RIGHT REGIONS
    // ==========================================
    'white-12-bl': { id: 'white-12-bl', type: 'REGULAR', label: '12', value: 12, requiresEqualDice: true, row: 6, col: 1, x: 5.5, y: 61.0, connectedCellIds: ['activate-4-fl', 'white-2-bl'] },
    'white-2-bl': { id: 'white-2-bl', type: 'REGULAR', label: '2', value: 2, requiresEqualDice: true, row: 6, col: 2, x: 13.0, y: 61.0, connectedCellIds: ['white-12-bl', 'white-5-bl'] },
    'white-5-bl': { id: 'white-5-bl', type: 'REGULAR', label: '5', value: 5, row: 5, col: 3, x: 20.5, y: 53.0, connectedCellIds: ['white-2-bl', 'monster-grey-hound', 'activate-6-bl'] },

    'activate-6-bl': { id: 'activate-6-bl', type: 'GRAY_ACTIVATION', label: '6 (Star)', value: 6, row: 7, col: 3, x: 14.0, y: 69.0, connectedCellIds: ['white-5-bl', 'white-2-bl-gem', 'monster-white-wolf'] },
    'white-2-bl-gem': { id: 'white-2-bl-gem', type: 'REGULAR', label: '2 (Gem)', value: 2, requiresEqualDice: true, row: 7, col: 4, x: 21.0, y: 66.5, connectedCellIds: ['activate-6-bl', 'white-5-bl-low', 'white-6-bm'] },
    'white-5-bl-low': { id: 'white-5-bl-low', type: 'REGULAR', label: '5', value: 5, row: 8, col: 4, x: 21.0, y: 77.5, connectedCellIds: ['white-2-bl-gem', 'monster-white-wolf'] },
    'white-6-bm': { id: 'white-6-bm', type: 'REGULAR', label: '6', value: 6, row: 7, col: 5, x: 28.5, y: 66.5, connectedCellIds: ['white-2-bl-gem', 'white-8-bm'] },
    'white-8-bm': { id: 'white-8-bm', type: 'REGULAR', label: '8', value: 8, requiresEqualDice: true, row: 7, col: 6, x: 35.5, y: 66.5, connectedCellIds: ['white-6-bm', 'white-7-bm-low'] },
    'white-7-bm-low': { id: 'white-7-bm-low', type: 'REGULAR', label: '7', value: 7, row: 7, col: 7, x: 42.0, y: 68.0, connectedCellIds: ['white-8-bm', 'white-5-boss-left', 'monster-primal-hare'] },

    'monster-white-wolf': {
      id: 'monster-white-wolf',
      type: 'MONSTER',
      label: 'White Wolf',
      monsterId: 'white-wolf',
      row: 10,
      col: 5,
      x: 29.5,
      y: 82.5,
      connectedCellIds: ['white-5-bl-low', 'activate-6-bl'],
      monsterLifeBoxes: [
        { cellId: 'm-wolf-4', value: 4 },
        { cellId: 'm-wolf-5', value: 5 },
        { cellId: 'm-wolf-8', value: 8, requiresActivationCellId: 'activate-6-bl' },
      ],
    },

    'monster-primal-hare': {
      id: 'monster-primal-hare',
      type: 'MONSTER',
      label: 'Primal Hare',
      monsterId: 'primal-hare',
      row: 9,
      col: 7,
      x: 49.0,
      y: 77.5,
      connectedCellIds: ['white-7-bm-low', 'white-6-bm-right', 'activate-8-bm'],
      monsterLifeBoxes: [
        { cellId: 'm-primal-2', value: 2 },
        { cellId: 'm-primal-12', value: 12, requiresActivationCellId: 'activate-8-bm' },
      ],
    },
    'activate-8-bm': { id: 'activate-8-bm', type: 'GRAY_ACTIVATION', label: '8 (Star)', value: 8, row: 7, col: 8, x: 58.0, y: 62.5, connectedCellIds: ['white-9-bm', 'monster-primal-hare'] },
    'white-6-bm-right': { id: 'white-6-bm-right', type: 'REGULAR', label: '6', value: 6, row: 8, col: 8, x: 56.5, y: 73.0, connectedCellIds: ['monster-primal-hare', 'white-10-bm-right'] },
    'white-10-bm-right': { id: 'white-10-bm-right', type: 'REGULAR', label: '10', value: 10, row: 8, col: 9, x: 63.0, y: 69.0, connectedCellIds: ['white-6-bm-right', 'white-9-bm', 'white-8-br-low'] },
    'white-9-bm': { id: 'white-9-bm', type: 'REGULAR', label: '9', value: 9, row: 7, col: 9, x: 64.0, y: 62.5, connectedCellIds: ['white-10-bm-right', 'activate-8-bm', 'white-7-br-mid'] },
    'white-7-br-mid': { id: 'white-7-br-mid', type: 'REGULAR', label: '7', value: 7, row: 7, col: 10, x: 67.0, y: 57.0, connectedCellIds: ['white-9-bm', 'white-4-mr'] },
    'chest-3': { id: 'chest-3', type: 'CHEST', label: 'Chest 3 (+3 HP & Gem)', row: 5, col: 10, x: 76.5, y: 50.5, connectedCellIds: ['white-gem-12-tr', 'white-4-mr'], chestReward: 'EXTRA_HEALTH' },
    'white-4-mr': { id: 'white-4-mr', type: 'REGULAR', label: '4', value: 4, row: 6, col: 10, x: 71.5, y: 55.5, connectedCellIds: ['chest-3', 'white-7-br-mid'] },
    'white-8-br-low': { id: 'white-8-br-low', type: 'REGULAR', label: '8', value: 8, requiresEqualDice: true, row: 8, col: 10, x: 73.0, y: 69.0, connectedCellIds: ['white-10-bm-right', 'activate-2-br', 'monster-punk-hare'] },
    'activate-2-br': { id: 'activate-2-br', type: 'GRAY_ACTIVATION', label: '2 (Star)', value: 2, row: 8, col: 11, x: 81.0, y: 69.0, connectedCellIds: ['white-8-br-low', 'monster-punk-hare'] },
    'monster-punk-hare': {
      id: 'monster-punk-hare',
      type: 'MONSTER',
      label: 'Punk Hare',
      monsterId: 'punk-hare',
      row: 9,
      col: 10,
      x: 76.5,
      y: 78.0,
      connectedCellIds: ['white-8-br-low', 'activate-2-br'],
      monsterLifeBoxes: [
        { cellId: 'm-punk-3', value: 3 },
        { cellId: 'm-punk-11', value: 11, requiresActivationCellId: 'activate-2-br' },
      ],
    },
  },
  monsters: {
    'purple-pup': {
      id: 'purple-pup',
      name: 'Purple Pup',
      isBoss: false,
      rewardGems: 2,
      lifePenaltyOnDefeat: 0,
      lifeBoxes: [
        { cellId: 'm-purple-3', value: 3 },
        { cellId: 'm-purple-4', value: 4 },
        { cellId: 'm-purple-11', value: 11, requiresActivationCellId: 'activate-10-tl' },
      ],
    },
    'green-growler': {
      id: 'green-growler',
      name: 'Green Growler',
      isBoss: false,
      rewardGems: 2,
      lifePenaltyOnDefeat: 0,
      lifeBoxes: [
        { cellId: 'm-growler-3', value: 3 },
        { cellId: 'm-growler-5', value: 5 },
        { cellId: 'm-growler-9', value: 9, requiresActivationCellId: 'activate-9-tr' },
      ],
    },
    'grey-hound': {
      id: 'grey-hound',
      name: 'Grey Hound',
      isBoss: false,
      rewardGems: 2,
      lifePenaltyOnDefeat: 0,
      lifeBoxes: [
        { cellId: 'm-grey-6', value: 6 },
        { cellId: 'm-grey-8', value: 8 },
        { cellId: 'm-grey-10', value: 10, requiresActivationCellId: 'activate-10-tl' },
      ],
    },
    'white-wolf': {
      id: 'white-wolf',
      name: 'White Wolf',
      isBoss: false,
      rewardGems: 2,
      lifePenaltyOnDefeat: 0,
      lifeBoxes: [
        { cellId: 'm-wolf-4', value: 4 },
        { cellId: 'm-wolf-5', value: 5 },
        { cellId: 'm-wolf-8', value: 8, requiresActivationCellId: 'activate-6-bl' },
      ],
    },
    'primal-hare': {
      id: 'primal-hare',
      name: 'Primal Hare',
      isBoss: false,
      rewardGems: 3,
      lifePenaltyOnDefeat: 0,
      lifeBoxes: [
        { cellId: 'm-primal-2', value: 2 },
        { cellId: 'm-primal-12', value: 12, requiresActivationCellId: 'activate-8-bm' },
      ],
    },
    'punk-hare': {
      id: 'punk-hare',
      name: 'Punk Hare',
      isBoss: false,
      rewardGems: 3,
      lifePenaltyOnDefeat: 0,
      lifeBoxes: [
        { cellId: 'm-punk-3', value: 3 },
        { cellId: 'm-punk-11', value: 11, requiresActivationCellId: 'activate-2-br' },
      ],
    },
    'boss-bearpion': {
      id: 'boss-bearpion',
      name: 'Beefy Bearpion',
      isBoss: true,
      rewardGems: 5,
      lifePenaltyOnDefeat: 2,
      lifeBoxes: [
        { cellId: 'm-boss-3', value: 3 },
        { cellId: 'm-boss-4', value: 4 },
        { cellId: 'm-boss-5', value: 5 },
        { cellId: 'm-boss-8', value: 8 },
        { cellId: 'm-boss-11a', value: 11 },
        { cellId: 'm-boss-11b', value: 11, requiresActivationCellId: 'activate-8-boss' },
      ],
    },
  },
};
