import { DungeonMapDefinition } from '../types';

export const ANNOYED_ANIMALS_MAP: DungeonMapDefinition = {
  id: 'annoyed-animals',
  name: 'Annoyed Animals',
  difficulty: 'Novice',
  startCellIds: ['start-2-tl', 'start-3-tr', 'start-4-tr', 'start-6-bl', 'start-2-br'],
  cells: {
    // Green Start Spaces
    'start-2-tl': {
      id: 'start-2-tl',
      type: 'START',
      label: '2',
      value: 2,
      row: 0,
      col: 2,
      x: 13.7,
      y: 4.5,
      connectedCellIds: ['reg-9-tl', 'reg-4-tc'],
    },
    'start-3-tr': {
      id: 'start-3-tr',
      type: 'START',
      label: '3',
      value: 3,
      row: 0,
      col: 10,
      x: 54.8,
      y: 4.5,
      connectedCellIds: ['reg-4-tr', 'm-growler-3'],
    },
    'start-4-tr': {
      id: 'start-4-tr',
      type: 'START',
      label: '4',
      value: 4,
      row: 0,
      col: 11,
      x: 60.0,
      y: 4.5,
      connectedCellIds: ['start-3-tr', 'reg-5-tr'],
    },
    'start-6-bl': {
      id: 'start-6-bl',
      type: 'START',
      label: '6',
      value: 6,
      row: 6,
      col: 1,
      x: 8.6,
      y: 46.1,
      connectedCellIds: ['reg-2-bl', 'm-wolf-4'],
    },
    'start-2-br': {
      id: 'start-2-br',
      type: 'START',
      label: '2',
      value: 2,
      row: 7,
      col: 10,
      x: 54.8,
      y: 53.0,
      connectedCellIds: ['reg-9-br', 'reg-8-br'],
    },

    // Chests
    'chest-black-dice': {
      id: 'chest-black-dice',
      type: 'CHEST',
      label: 'Chest (+3 Black Dice)',
      row: 5,
      col: 0,
      x: 3.5,
      y: 39.2,
      connectedCellIds: ['reg-12-bl'],
      chestReward: 'BLACK_DICE',
    },
    'chest-11-gold': {
      id: 'chest-11-gold',
      type: 'CHEST',
      label: 'Chest 11 (+1 Torch)',
      row: 2,
      col: 4,
      x: 24.0,
      y: 18.4,
      connectedCellIds: ['reg-7-tc', 'reg-12-tc', 'reg-3-tc'],
      chestReward: 'TORCH',
    },
    'chest-extra-health': {
      id: 'chest-extra-health',
      type: 'CHEST',
      label: 'Chest (+3 Health & Gem)',
      row: 5,
      col: 10,
      x: 54.8,
      y: 39.2,
      connectedCellIds: ['m-punk-11', 'reg-9-br'],
      chestReward: 'EXTRA_HEALTH',
    },

    // Regular spaces
    'reg-9-tl': {
      id: 'reg-9-tl',
      type: 'REGULAR',
      label: '9',
      value: 9,
      row: 1,
      col: 2,
      x: 13.7,
      y: 11.4,
      connectedCellIds: ['start-2-tl', 'reg-6-tl'],
    },
    'reg-6-tl': {
      id: 'reg-6-tl',
      type: 'REGULAR',
      label: '6',
      value: 6,
      row: 2,
      col: 2,
      x: 13.7,
      y: 18.4,
      connectedCellIds: ['reg-9-tl', 'm-grey-6'],
    },
    'reg-4-tc': {
      id: 'reg-4-tc',
      type: 'REGULAR',
      label: '4',
      value: 4,
      row: 0,
      col: 3,
      x: 18.9,
      y: 4.5,
      connectedCellIds: ['start-2-tl', 'm-purple-3', 'reg-7-tc'],
    },
    'reg-7-tc': {
      id: 'reg-7-tc',
      type: 'REGULAR',
      label: '7',
      value: 7,
      row: 1,
      col: 3,
      x: 18.9,
      y: 11.4,
      connectedCellIds: ['reg-4-tc', 'chest-11-gold', 'reg-3-tc'],
    },
    'reg-3-tc': {
      id: 'reg-3-tc',
      type: 'REGULAR',
      label: '3',
      value: 3,
      row: 1,
      col: 4,
      x: 24.0,
      y: 11.4,
      connectedCellIds: ['reg-7-tc', 'chest-11-gold', 'reg-10-tc'],
    },
    'reg-10-tc': {
      id: 'reg-10-tc',
      type: 'REGULAR',
      label: '10',
      value: 10,
      row: 1,
      col: 5,
      x: 29.1,
      y: 11.4,
      connectedCellIds: ['reg-3-tc', 'm-boss-3'],
    },
    'reg-5-tr': {
      id: 'reg-5-tr',
      type: 'REGULAR',
      label: '5',
      value: 5,
      row: 1,
      col: 11,
      x: 60.0,
      y: 11.4,
      connectedCellIds: ['start-4-tr', 'reg-8-tr'],
    },
    'reg-8-tr': {
      id: 'reg-8-tr',
      type: 'REGULAR',
      label: '8',
      value: 8,
      row: 2,
      col: 11,
      x: 60.0,
      y: 18.4,
      connectedCellIds: ['reg-5-tr', 'reg-9-tr'],
    },
    'reg-9-tr': {
      id: 'reg-9-tr',
      type: 'REGULAR',
      label: '9',
      value: 9,
      row: 2,
      col: 10,
      x: 54.8,
      y: 18.4,
      connectedCellIds: ['reg-8-tr', 'm-growler-9'],
    },
    'reg-12-bl': {
      id: 'reg-12-bl',
      type: 'REGULAR',
      label: '12',
      value: 12,
      row: 5,
      col: 1,
      x: 8.6,
      y: 39.2,
      connectedCellIds: ['chest-black-dice', 'reg-2-bl'],
    },
    'reg-2-bl': {
      id: 'reg-2-bl',
      type: 'REGULAR',
      label: '2',
      value: 2,
      row: 5,
      col: 2,
      x: 13.7,
      y: 39.2,
      connectedCellIds: ['reg-12-bl', 'start-6-bl'],
    },

    // Monster 1: Purple Pup
    'm-purple-3': {
      id: 'm-purple-3',
      type: 'MONSTER',
      label: 'Purple Pup: 3',
      value: 3,
      row: 0,
      col: 4,
      x: 24.0,
      y: 4.5,
      monsterId: 'purple-pup',
      connectedCellIds: ['reg-4-tc', 'm-purple-4'],
    },
    'm-purple-4': {
      id: 'm-purple-4',
      type: 'MONSTER',
      label: 'Purple Pup: 4',
      value: 4,
      row: 0,
      col: 5,
      x: 29.1,
      y: 4.5,
      monsterId: 'purple-pup',
      connectedCellIds: ['m-purple-3', 'm-purple-11'],
    },
    'm-purple-11': {
      id: 'm-purple-11',
      type: 'MONSTER',
      label: 'Purple Pup: 11',
      value: 11,
      row: 0,
      col: 6,
      x: 34.3,
      y: 4.5,
      monsterId: 'purple-pup',
      connectedCellIds: ['m-purple-4', 'reg-10-tc'],
    },

    // Monster 2: Green Growler
    'm-growler-3': {
      id: 'm-growler-3',
      type: 'MONSTER',
      label: 'Green Growler: 3',
      value: 3,
      row: 1,
      col: 9,
      x: 49.7,
      y: 11.4,
      monsterId: 'green-growler',
      connectedCellIds: ['start-3-tr', 'm-growler-5'],
    },
    'm-growler-5': {
      id: 'm-growler-5',
      type: 'MONSTER',
      label: 'Green Growler: 5',
      value: 5,
      row: 1,
      col: 10,
      x: 54.8,
      y: 11.4,
      monsterId: 'green-growler',
      connectedCellIds: ['m-growler-3', 'm-growler-9'],
    },
    'm-growler-9': {
      id: 'm-growler-9',
      type: 'MONSTER',
      label: 'Green Growler: 9',
      value: 9,
      row: 2,
      col: 10,
      x: 54.8,
      y: 18.4,
      monsterId: 'green-growler',
      connectedCellIds: ['m-growler-5', 'reg-9-tr'],
    },

    // Monster 3: Grey Hound
    'm-grey-6': {
      id: 'm-grey-6',
      type: 'MONSTER',
      label: 'Grey Hound: 6',
      value: 6,
      row: 2,
      col: 3,
      x: 18.9,
      y: 18.4,
      monsterId: 'grey-hound',
      connectedCellIds: ['reg-6-tl', 'm-grey-8'],
    },
    'm-grey-8': {
      id: 'm-grey-8',
      type: 'MONSTER',
      label: 'Grey Hound: 8',
      value: 8,
      row: 2,
      col: 4,
      x: 24.0,
      y: 18.4,
      monsterId: 'grey-hound',
      connectedCellIds: ['m-grey-6', 'm-grey-10'],
    },
    'm-grey-10': {
      id: 'm-grey-10',
      type: 'MONSTER',
      label: 'Grey Hound: 10',
      value: 10,
      row: 3,
      col: 4,
      x: 24.0,
      y: 25.3,
      monsterId: 'grey-hound',
      connectedCellIds: ['m-grey-8', 'reg-3-tc'],
    },

    // Monster 4: White Wolf
    'm-wolf-4': {
      id: 'm-wolf-4',
      type: 'MONSTER',
      label: 'White Wolf: 4',
      value: 4,
      row: 7,
      col: 3,
      x: 18.9,
      y: 53.0,
      monsterId: 'white-wolf',
      connectedCellIds: ['start-6-bl', 'm-wolf-5'],
    },
    'm-wolf-5': {
      id: 'm-wolf-5',
      type: 'MONSTER',
      label: 'White Wolf: 5',
      value: 5,
      row: 7,
      col: 4,
      x: 24.0,
      y: 53.0,
      monsterId: 'white-wolf',
      connectedCellIds: ['m-wolf-4', 'm-wolf-8'],
    },
    'm-wolf-8': {
      id: 'm-wolf-8',
      type: 'MONSTER',
      label: 'White Wolf: 8',
      value: 8,
      row: 7,
      col: 5,
      x: 29.1,
      y: 53.0,
      monsterId: 'white-wolf',
      connectedCellIds: ['m-wolf-5'],
    },

    // Monster 5: Primal Hare
    'm-primal-2': {
      id: 'm-primal-2',
      type: 'MONSTER',
      label: 'Primal Hare: 2',
      value: 2,
      row: 7,
      col: 6,
      x: 34.3,
      y: 53.0,
      monsterId: 'primal-hare',
      connectedCellIds: ['m-primal-12'],
    },
    'm-primal-12': {
      id: 'm-primal-12',
      type: 'MONSTER',
      label: 'Primal Hare: 12',
      value: 12,
      row: 7,
      col: 7,
      x: 39.4,
      y: 53.0,
      monsterId: 'primal-hare',
      connectedCellIds: ['m-primal-2'],
    },

    // Monster 6: Punk Hare
    'm-punk-3': {
      id: 'm-punk-3',
      type: 'MONSTER',
      label: 'Punk Hare: 3',
      value: 3,
      row: 8,
      col: 9,
      x: 49.7,
      y: 60.0,
      monsterId: 'punk-hare',
      connectedCellIds: ['m-punk-11'],
    },
    'm-punk-11': {
      id: 'm-punk-11',
      type: 'MONSTER',
      label: 'Punk Hare: 11',
      value: 11,
      row: 8,
      col: 10,
      x: 54.8,
      y: 60.0,
      monsterId: 'punk-hare',
      connectedCellIds: ['m-punk-3'],
    },

    // Boss Monster: Beefy Bearpion
    'm-boss-3': {
      id: 'm-boss-3',
      type: 'MONSTER',
      label: 'Boss: 3',
      value: 3,
      row: 4,
      col: 6,
      x: 34.3,
      y: 32.3,
      monsterId: 'boss-bearpion',
      connectedCellIds: ['reg-10-tc', 'm-boss-4'],
    },
    'm-boss-4': {
      id: 'm-boss-4',
      type: 'MONSTER',
      label: 'Boss: 4',
      value: 4,
      row: 4,
      col: 7,
      x: 39.4,
      y: 32.3,
      monsterId: 'boss-bearpion',
      connectedCellIds: ['m-boss-3', 'm-boss-5'],
    },
    'm-boss-5': {
      id: 'm-boss-5',
      type: 'MONSTER',
      label: 'Boss: 5',
      value: 5,
      row: 5,
      col: 6,
      x: 34.3,
      y: 39.2,
      monsterId: 'boss-bearpion',
      connectedCellIds: ['m-boss-4', 'm-boss-8'],
    },
    'm-boss-8': {
      id: 'm-boss-8',
      type: 'MONSTER',
      label: 'Boss: 8',
      value: 8,
      row: 5,
      col: 7,
      x: 39.4,
      y: 39.2,
      monsterId: 'boss-bearpion',
      connectedCellIds: ['m-boss-5', 'm-boss-11'],
    },
    'm-boss-11': {
      id: 'm-boss-11',
      type: 'MONSTER',
      label: 'Boss: 11',
      value: 11,
      row: 6,
      col: 7,
      x: 39.4,
      y: 46.1,
      monsterId: 'boss-bearpion',
      connectedCellIds: ['m-boss-8'],
    },
  },
  monsters: {
    'purple-pup': {
      id: 'purple-pup',
      name: 'Purple Pup',
      isBoss: false,
      rewardGems: 2,
      lifePenaltyOnDefeat: 0,
      lifeBoxes: [
        { cellId: 'm-purple-3', value: 3 },
        { cellId: 'm-purple-4', value: 4 },
        { cellId: 'm-purple-11', value: 11 },
      ],
    },
    'green-growler': {
      id: 'green-growler',
      name: 'Green Growler',
      isBoss: false,
      rewardGems: 2,
      lifePenaltyOnDefeat: 0,
      lifeBoxes: [
        { cellId: 'm-growler-3', value: 3 },
        { cellId: 'm-growler-5', value: 5 },
        { cellId: 'm-growler-9', value: 9 },
      ],
    },
    'grey-hound': {
      id: 'grey-hound',
      name: 'Grey Hound',
      isBoss: false,
      rewardGems: 2,
      lifePenaltyOnDefeat: 0,
      lifeBoxes: [
        { cellId: 'm-grey-6', value: 6 },
        { cellId: 'm-grey-8', value: 8 },
        { cellId: 'm-grey-10', value: 10 },
      ],
    },
    'white-wolf': {
      id: 'white-wolf',
      name: 'White Wolf',
      isBoss: false,
      rewardGems: 2,
      lifePenaltyOnDefeat: 0,
      lifeBoxes: [
        { cellId: 'm-wolf-4', value: 4 },
        { cellId: 'm-wolf-5', value: 5 },
        { cellId: 'm-wolf-8', value: 8 },
      ],
    },
    'primal-hare': {
      id: 'primal-hare',
      name: 'Primal Hare',
      isBoss: false,
      rewardGems: 3,
      lifePenaltyOnDefeat: 0,
      lifeBoxes: [
        { cellId: 'm-primal-2', value: 2 },
        { cellId: 'm-primal-12', value: 12 },
      ],
    },
    'punk-hare': {
      id: 'punk-hare',
      name: 'Punk Hare',
      isBoss: false,
      rewardGems: 3,
      lifePenaltyOnDefeat: 0,
      lifeBoxes: [
        { cellId: 'm-punk-3', value: 3 },
        { cellId: 'm-punk-11', value: 11 },
      ],
    },
    'boss-bearpion': {
      id: 'boss-bearpion',
      name: 'Beefy Bearpion',
      isBoss: true,
      rewardGems: 5,
      lifePenaltyOnDefeat: 2,
      lifeBoxes: [
        { cellId: 'm-boss-3', value: 3 },
        { cellId: 'm-boss-4', value: 4 },
        { cellId: 'm-boss-5', value: 5 },
        { cellId: 'm-boss-8', value: 8 },
        { cellId: 'm-boss-11', value: 11 },
      ],
    },
  },
};
