import { DungeonMapDefinition } from '../types';

export const ANNOYED_ANIMALS_MAP: DungeonMapDefinition = {
  id: 'annoyed-animals',
  name: 'Annoyed Animals',
  difficulty: 'Novice',
  startCellIds: ['start-2', 'start-7', 'start-12'],
  cells: {
    // Start Spaces (Green)
    'start-2': {
      id: 'start-2',
      type: 'START',
      label: '2',
      value: 2,
      row: 0,
      col: 2,
      connectedCellIds: ['reg-3-1', 'reg-4-1', 'chest-1'],
    },
    'start-7': {
      id: 'start-7',
      type: 'START',
      label: '7',
      value: 7,
      row: 3,
      col: 1,
      connectedCellIds: ['reg-6-1', 'gray-5-1', 'reg-8-1'],
    },
    'start-12': {
      id: 'start-12',
      type: 'START',
      label: '12',
      value: 12,
      row: 7,
      col: 0,
      connectedCellIds: ['reg-10-1', 'reg-11-1', 'chest-2'],
    },

    // Chests
    'chest-1': {
      id: 'chest-1',
      type: 'CHEST',
      label: 'Chest (+3 Black Dice)',
      row: 1,
      col: 1,
      connectedCellIds: ['start-2', 'reg-3-1', 'reg-5-1'],
      chestReward: 'BLACK_DICE',
    },
    'chest-2': {
      id: 'chest-2',
      type: 'CHEST',
      label: 'Chest (+1 Torch)',
      row: 6,
      col: 1,
      connectedCellIds: ['start-12', 'reg-11-1', 'reg-9-1'],
      chestReward: 'TORCH',
    },
    'chest-3': {
      id: 'chest-3',
      type: 'CHEST',
      label: 'Chest (+3 Health & Gem)',
      row: 3,
      col: 4,
      connectedCellIds: ['m1-box-7', 'reg-8-2', 'reg-6-2'],
      chestReward: 'EXTRA_HEALTH',
    },

    // Regular spaces
    'reg-3-1': {
      id: 'reg-3-1',
      type: 'REGULAR',
      label: '3',
      value: 3,
      row: 0,
      col: 3,
      connectedCellIds: ['start-2', 'chest-1', 'm1-box-6'],
    },
    'reg-4-1': {
      id: 'reg-4-1',
      type: 'REGULAR',
      label: '4',
      value: 4,
      row: 1,
      col: 2,
      connectedCellIds: ['start-2', 'reg-5-1', 'reg-6-1'],
    },
    'reg-5-1': {
      id: 'reg-5-1',
      type: 'REGULAR',
      label: '5',
      value: 5,
      row: 2,
      col: 2,
      connectedCellIds: ['reg-4-1', 'chest-1', 'm1-box-6'],
    },
    'reg-6-1': {
      id: 'reg-6-1',
      type: 'REGULAR',
      label: '6',
      value: 6,
      row: 3,
      col: 2,
      connectedCellIds: ['start-7', 'reg-4-1', 'gray-5-1'],
    },
    'gray-5-1': {
      id: 'gray-5-1',
      type: 'GRAY_ACTIVATION',
      label: '5 (Gray)',
      value: 5,
      row: 4,
      col: 2,
      connectedCellIds: ['start-7', 'reg-6-1', 'm2-box-5'],
    },
    'reg-8-1': {
      id: 'reg-8-1',
      type: 'REGULAR',
      label: '8',
      value: 8,
      row: 5,
      col: 2,
      connectedCellIds: ['start-7', 'reg-9-1', 'gray-9-1'],
    },
    'gray-9-1': {
      id: 'gray-9-1',
      type: 'GRAY_ACTIVATION',
      label: '9 (Gray)',
      value: 9,
      row: 6,
      col: 2,
      connectedCellIds: ['reg-8-1', 'boss-box-9'],
    },
    'reg-9-1': {
      id: 'reg-9-1',
      type: 'REGULAR',
      label: '9',
      value: 9,
      row: 7,
      col: 2,
      connectedCellIds: ['start-12', 'chest-2', 'reg-8-1'],
    },
    'reg-10-1': {
      id: 'reg-10-1',
      type: 'REGULAR',
      label: '10',
      value: 10,
      row: 8,
      col: 1,
      connectedCellIds: ['start-12', 'reg-11-1'],
    },
    'reg-11-1': {
      id: 'reg-11-1',
      type: 'REGULAR',
      label: '11',
      value: 11,
      row: 8,
      col: 2,
      connectedCellIds: ['reg-10-1', 'start-12', 'chest-2', 'm2-box-10'],
    },

    // Post-Monster spaces
    'reg-6-2': {
      id: 'reg-6-2',
      type: 'REGULAR',
      label: '6',
      value: 6,
      row: 2,
      col: 6,
      connectedCellIds: ['m1-box-8', 'chest-3', 'boss-box-7'],
    },
    'reg-8-2': {
      id: 'reg-8-2',
      type: 'REGULAR',
      label: '8',
      value: 8,
      row: 5,
      col: 6,
      connectedCellIds: ['m2-box-10', 'chest-3', 'boss-box-11'],
    },

    // Monster 1: Angry Boar
    'm1-box-6': {
      id: 'm1-box-6',
      type: 'MONSTER',
      label: 'Boar: 6',
      value: 6,
      row: 0,
      col: 4,
      monsterId: 'boar',
      connectedCellIds: ['reg-3-1', 'reg-5-1', 'm1-box-7'],
    },
    'm1-box-7': {
      id: 'm1-box-7',
      type: 'MONSTER',
      label: 'Boar: 7',
      value: 7,
      row: 0,
      col: 5,
      monsterId: 'boar',
      connectedCellIds: ['m1-box-6', 'm1-box-8', 'chest-3'],
    },
    'm1-box-8': {
      id: 'm1-box-8',
      type: 'MONSTER',
      label: 'Boar: 8',
      value: 8,
      row: 1,
      col: 6,
      monsterId: 'boar',
      connectedCellIds: ['m1-box-7', 'reg-6-2'],
    },

    // Monster 2: Grumpy Bear
    'm2-box-5': {
      id: 'm2-box-5',
      type: 'MONSTER',
      label: 'Bear: 5 (Req Gray 5)',
      value: 5,
      row: 5,
      col: 3,
      monsterId: 'bear',
      requiresActivationCellId: 'gray-5-1',
      connectedCellIds: ['gray-5-1', 'm2-box-9'],
    },
    'm2-box-9': {
      id: 'm2-box-9',
      type: 'MONSTER',
      label: 'Bear: 9',
      value: 9,
      row: 6,
      col: 3,
      monsterId: 'bear',
      connectedCellIds: ['m2-box-5', 'm2-box-10'],
    },
    'm2-box-10': {
      id: 'm2-box-10',
      type: 'MONSTER',
      label: 'Bear: 10',
      value: 10,
      row: 7,
      col: 3,
      monsterId: 'bear',
      connectedCellIds: ['m2-box-9', 'reg-11-1', 'reg-8-2'],
    },

    // Boss Monster: Dragon
    'boss-box-7': {
      id: 'boss-box-7',
      type: 'MONSTER',
      label: 'Boss: 7',
      value: 7,
      row: 2,
      col: 8,
      monsterId: 'dragon',
      connectedCellIds: ['reg-6-2', 'boss-box-8'],
    },
    'boss-box-8': {
      id: 'boss-box-8',
      type: 'MONSTER',
      label: 'Boss: 8',
      value: 8,
      row: 3,
      col: 8,
      monsterId: 'dragon',
      connectedCellIds: ['boss-box-7', 'boss-box-9'],
    },
    'boss-box-9': {
      id: 'boss-box-9',
      type: 'MONSTER',
      label: 'Boss: 9 (Req Gray 9)',
      value: 9,
      row: 4,
      col: 8,
      monsterId: 'dragon',
      requiresActivationCellId: 'gray-9-1',
      connectedCellIds: ['gray-9-1', 'boss-box-8', 'boss-box-10'],
    },
    'boss-box-10': {
      id: 'boss-box-10',
      type: 'MONSTER',
      label: 'Boss: 10',
      value: 10,
      row: 5,
      col: 8,
      monsterId: 'dragon',
      connectedCellIds: ['boss-box-9', 'boss-box-11'],
    },
    'boss-box-11': {
      id: 'boss-box-11',
      type: 'MONSTER',
      label: 'Boss: 11',
      value: 11,
      row: 6,
      col: 8,
      monsterId: 'dragon',
      connectedCellIds: ['boss-box-10', 'reg-8-2'],
    },
  },
  monsters: {
    boar: {
      id: 'boar',
      name: 'Angry Boar',
      isBoss: false,
      rewardGems: 2,
      lifePenaltyOnDefeat: 0,
      lifeBoxes: [
        { cellId: 'm1-box-6', value: 6 },
        { cellId: 'm1-box-7', value: 7 },
        { cellId: 'm1-box-8', value: 8 },
      ],
    },
    bear: {
      id: 'bear',
      name: 'Grumpy Bear',
      isBoss: false,
      rewardGems: 3,
      lifePenaltyOnDefeat: 1,
      lifeBoxes: [
        { cellId: 'm2-box-5', value: 5, requiresActivationCellId: 'gray-5-1' },
        { cellId: 'm2-box-9', value: 9 },
        { cellId: 'm2-box-10', value: 10 },
      ],
    },
    dragon: {
      id: 'dragon',
      name: 'Elder Dragon',
      isBoss: true,
      rewardGems: 5,
      lifePenaltyOnDefeat: 2,
      lifeBoxes: [
        { cellId: 'boss-box-7', value: 7 },
        { cellId: 'boss-box-8', value: 8 },
        { cellId: 'boss-box-9', value: 9, requiresActivationCellId: 'gray-9-1' },
        { cellId: 'boss-box-10', value: 10 },
        { cellId: 'boss-box-11', value: 11 },
      ],
    },
  },
};
