import { DungeonMapDefinition } from '../types';

export const CLUMSY_CULTISTS_MAP: DungeonMapDefinition = {
  id: 'clumsy-cultists',
  name: 'Clumsy Cultists',
  difficulty: 'Easy',
  startCellIds: ['start-3', 'start-6', 'start-11'],
  cells: {
    'start-3': {
      id: 'start-3',
      type: 'START',
      label: '3',
      value: 3,
      row: 0,
      col: 0,
      connectedCellIds: ['reg-4-1', 'chest-1'],
    },
    'start-6': {
      id: 'start-6',
      type: 'START',
      label: '6',
      value: 6,
      row: 2,
      col: 0,
      connectedCellIds: ['reg-7-1', 'gray-6-1', 'reg-8-1'],
    },
    'start-11': {
      id: 'start-11',
      type: 'START',
      label: '11',
      value: 11,
      row: 4,
      col: 0,
      connectedCellIds: ['reg-10-1', 'chest-2'],
    },

    'chest-1': {
      id: 'chest-1',
      type: 'CHEST',
      label: 'Chest (+3 Black Dice)',
      row: 0,
      col: 1,
      connectedCellIds: ['start-3', 'm1-box-5'],
      chestReward: 'BLACK_DICE',
    },
    'chest-2': {
      id: 'chest-2',
      type: 'CHEST',
      label: 'Chest (+1 Torch)',
      row: 4,
      col: 1,
      connectedCellIds: ['start-11', 'm2-box-9'],
      chestReward: 'TORCH',
    },

    'reg-4-1': {
      id: 'reg-4-1',
      type: 'REGULAR',
      label: '4',
      value: 4,
      row: 1,
      col: 1,
      connectedCellIds: ['start-3', 'reg-5-1'],
    },
    'reg-5-1': {
      id: 'reg-5-1',
      type: 'REGULAR',
      label: '5',
      value: 5,
      row: 1,
      col: 2,
      connectedCellIds: ['reg-4-1', 'm1-box-5'],
    },
    'reg-7-1': {
      id: 'reg-7-1',
      type: 'REGULAR',
      label: '7',
      value: 7,
      row: 2,
      col: 1,
      connectedCellIds: ['start-6', 'gray-6-1'],
    },
    'gray-6-1': {
      id: 'gray-6-1',
      type: 'GRAY_ACTIVATION',
      label: '6 (Gray)',
      value: 6,
      row: 2,
      col: 2,
      connectedCellIds: ['reg-7-1', 'm1-box-6'],
    },
    'reg-8-1': {
      id: 'reg-8-1',
      type: 'REGULAR',
      label: '8',
      value: 8,
      row: 3,
      col: 1,
      connectedCellIds: ['start-6', 'gray-8-1'],
    },
    'gray-8-1': {
      id: 'gray-8-1',
      type: 'GRAY_ACTIVATION',
      label: '8 (Gray)',
      value: 8,
      row: 3,
      col: 2,
      connectedCellIds: ['reg-8-1', 'boss-box-8'],
    },
    'reg-10-1': {
      id: 'reg-10-1',
      type: 'REGULAR',
      label: '10',
      value: 10,
      row: 4,
      col: 2,
      connectedCellIds: ['start-11', 'm2-box-9'],
    },

    // Cultist Novice
    'm1-box-5': {
      id: 'm1-box-5',
      type: 'MONSTER',
      label: 'Cultist: 5',
      value: 5,
      row: 0,
      col: 3,
      monsterId: 'cultist',
      connectedCellIds: ['chest-1', 'reg-5-1', 'm1-box-6'],
    },
    'm1-box-6': {
      id: 'm1-box-6',
      type: 'MONSTER',
      label: 'Cultist: 6 (Req Gray 6)',
      value: 6,
      row: 1,
      col: 3,
      monsterId: 'cultist',
      requiresActivationCellId: 'gray-6-1',
      connectedCellIds: ['m1-box-5', 'gray-6-1', 'm1-box-7'],
    },
    'm1-box-7': {
      id: 'm1-box-7',
      type: 'MONSTER',
      label: 'Cultist: 7',
      value: 7,
      row: 1,
      col: 4,
      monsterId: 'cultist',
      connectedCellIds: ['m1-box-6'],
    },

    // Shadow Initiate
    'm2-box-9': {
      id: 'm2-box-9',
      type: 'MONSTER',
      label: 'Shadow: 9',
      value: 9,
      row: 4,
      col: 3,
      monsterId: 'shadow',
      connectedCellIds: ['chest-2', 'reg-10-1', 'm2-box-10'],
    },
    'm2-box-10': {
      id: 'm2-box-10',
      type: 'MONSTER',
      label: 'Shadow: 10',
      value: 10,
      row: 4,
      col: 4,
      monsterId: 'shadow',
      connectedCellIds: ['m2-box-9'],
    },

    // High Priest (Boss)
    'boss-box-6': {
      id: 'boss-box-6',
      type: 'MONSTER',
      label: 'High Priest: 6',
      value: 6,
      row: 2,
      col: 4,
      monsterId: 'high-priest',
      connectedCellIds: ['boss-box-8'],
    },
    'boss-box-8': {
      id: 'boss-box-8',
      type: 'MONSTER',
      label: 'High Priest: 8 (Req Gray 8)',
      value: 8,
      row: 3,
      col: 4,
      monsterId: 'high-priest',
      requiresActivationCellId: 'gray-8-1',
      connectedCellIds: ['gray-8-1', 'boss-box-6', 'boss-box-10'],
    },
    'boss-box-10': {
      id: 'boss-box-10',
      type: 'MONSTER',
      label: 'High Priest: 10',
      value: 10,
      row: 3,
      col: 5,
      monsterId: 'high-priest',
      connectedCellIds: ['boss-box-8'],
    },
  },
  monsters: {
    cultist: {
      id: 'cultist',
      name: 'Clumsy Cultist',
      isBoss: false,
      rewardGems: 3,
      lifePenaltyOnDefeat: 0,
      lifeBoxes: [
        { cellId: 'm1-box-5', value: 5 },
        { cellId: 'm1-box-6', value: 6, requiresActivationCellId: 'gray-6-1' },
        { cellId: 'm1-box-7', value: 7 },
      ],
    },
    shadow: {
      id: 'shadow',
      name: 'Shadow Initiate',
      isBoss: false,
      rewardGems: 3,
      lifePenaltyOnDefeat: 1,
      lifeBoxes: [
        { cellId: 'm2-box-9', value: 9 },
        { cellId: 'm2-box-10', value: 10 },
      ],
    },
    'high-priest': {
      id: 'high-priest',
      name: 'High Priest',
      isBoss: true,
      rewardGems: 6,
      lifePenaltyOnDefeat: 2,
      lifeBoxes: [
        { cellId: 'boss-box-6', value: 6 },
        { cellId: 'boss-box-8', value: 8, requiresActivationCellId: 'gray-8-1' },
        { cellId: 'boss-box-10', value: 10 },
      ],
    },
  },
};
