import { DungeonMapDefinition } from '../types';

export const DEFIANT_DINOSAURS_MAP: DungeonMapDefinition = {
  id: 'defiant-dinosaurs',
  name: 'Defiant Dinosaurs',
  difficulty: 'Expert',
  startCellIds: ['start-2', 'start-7', 'start-12'],
  cells: {
    'start-2': {
      id: 'start-2',
      type: 'START',
      label: '2',
      value: 2,
      row: 0,
      col: 0,
      connectedCellIds: ['reg-3-1', 'chest-1'],
    },
    'start-7': {
      id: 'start-7',
      type: 'START',
      label: '7',
      value: 7,
      row: 2,
      col: 0,
      connectedCellIds: ['reg-6-1', 'gray-6-1', 'reg-8-1'],
    },
    'start-12': {
      id: 'start-12',
      type: 'START',
      label: '12',
      value: 12,
      row: 4,
      col: 0,
      connectedCellIds: ['reg-11-1', 'chest-2'],
    },

    'chest-1': {
      id: 'chest-1',
      type: 'CHEST',
      label: 'Chest (+3 Black Dice)',
      row: 0,
      col: 1,
      connectedCellIds: ['start-2', 'm1-box-6'],
      chestReward: 'BLACK_DICE',
    },
    'chest-2': {
      id: 'chest-2',
      type: 'CHEST',
      label: 'Chest (+1 Torch)',
      row: 4,
      col: 1,
      connectedCellIds: ['start-12', 'm2-box-8'],
      chestReward: 'TORCH',
    },

    'reg-3-1': {
      id: 'reg-3-1',
      type: 'REGULAR',
      label: '3',
      value: 3,
      row: 1,
      col: 1,
      connectedCellIds: ['start-2', 'm1-box-6'],
    },
    'reg-6-1': {
      id: 'reg-6-1',
      type: 'REGULAR',
      label: '6',
      value: 6,
      row: 2,
      col: 1,
      connectedCellIds: ['start-7', 'gray-6-1'],
    },
    'gray-6-1': {
      id: 'gray-6-1',
      type: 'GRAY_ACTIVATION',
      label: '6 (Gray)',
      value: 6,
      row: 2,
      col: 2,
      connectedCellIds: ['reg-6-1', 'm1-box-7'],
    },
    'reg-8-1': {
      id: 'reg-8-1',
      type: 'REGULAR',
      label: '8',
      value: 8,
      row: 3,
      col: 1,
      connectedCellIds: ['start-7', 'gray-10-1'],
    },
    'gray-10-1': {
      id: 'gray-10-1',
      type: 'GRAY_ACTIVATION',
      label: '10 (Gray)',
      value: 10,
      row: 3,
      col: 2,
      connectedCellIds: ['reg-8-1', 'boss-box-10'],
    },
    'reg-11-1': {
      id: 'reg-11-1',
      type: 'REGULAR',
      label: '11',
      value: 11,
      row: 4,
      col: 2,
      connectedCellIds: ['start-12', 'm2-box-8'],
    },

    // Armored Dinosaur (Raptor) - Requires Armored Double-Pair
    'm1-box-6': {
      id: 'm1-box-6',
      type: 'MONSTER',
      label: 'Armored Raptor: 6 (Armored)',
      value: 6,
      row: 0,
      col: 3,
      monsterId: 'raptor',
      isArmored: true,
      connectedCellIds: ['chest-1', 'reg-3-1', 'm1-box-7'],
    },
    'm1-box-7': {
      id: 'm1-box-7',
      type: 'MONSTER',
      label: 'Armored Raptor: 7 (Req Gray 6)',
      value: 7,
      row: 1,
      col: 3,
      monsterId: 'raptor',
      requiresActivationCellId: 'gray-6-1',
      connectedCellIds: ['m1-box-6', 'gray-6-1'],
    },

    // Pterodactyl
    'm2-box-8': {
      id: 'm2-box-8',
      type: 'MONSTER',
      label: 'Pterodactyl: 8',
      value: 8,
      row: 4,
      col: 3,
      monsterId: 'ptero',
      connectedCellIds: ['chest-2', 'reg-11-1', 'm2-box-9'],
    },
    'm2-box-9': {
      id: 'm2-box-9',
      type: 'MONSTER',
      label: 'Pterodactyl: 9',
      value: 9,
      row: 4,
      col: 4,
      monsterId: 'ptero',
      connectedCellIds: ['m2-box-8'],
    },

    // T-Rex (Boss - Armored Dinosaur)
    'boss-box-6': {
      id: 'boss-box-6',
      type: 'MONSTER',
      label: 'T-Rex: 6',
      value: 6,
      row: 2,
      col: 4,
      monsterId: 'trex',
      connectedCellIds: ['boss-box-8'],
    },
    'boss-box-8': {
      id: 'boss-box-8',
      type: 'MONSTER',
      label: 'T-Rex: 8 (Armored)',
      value: 8,
      row: 2,
      col: 5,
      monsterId: 'trex',
      isArmored: true,
      connectedCellIds: ['boss-box-6', 'boss-box-10'],
    },
    'boss-box-10': {
      id: 'boss-box-10',
      type: 'MONSTER',
      label: 'T-Rex: 10 (Req Gray 10)',
      value: 10,
      row: 3,
      col: 5,
      monsterId: 'trex',
      requiresActivationCellId: 'gray-10-1',
      connectedCellIds: ['gray-10-1', 'boss-box-8'],
    },
  },
  monsters: {
    raptor: {
      id: 'raptor',
      name: 'Armored Raptor',
      isBoss: false,
      rewardGems: 4,
      lifePenaltyOnDefeat: 1,
      lifeBoxes: [
        { cellId: 'm1-box-6', value: 6, isArmored: true },
        { cellId: 'm1-box-7', value: 7, requiresActivationCellId: 'gray-6-1' },
      ],
    },
    ptero: {
      id: 'ptero',
      name: 'Pterodactyl',
      isBoss: false,
      rewardGems: 3,
      lifePenaltyOnDefeat: 1,
      lifeBoxes: [
        { cellId: 'm2-box-8', value: 8 },
        { cellId: 'm2-box-9', value: 9 },
      ],
    },
    trex: {
      id: 'trex',
      name: 'Tyrannosaurus Rex',
      isBoss: true,
      rewardGems: 7,
      lifePenaltyOnDefeat: 3,
      lifeBoxes: [
        { cellId: 'boss-box-6', value: 6 },
        { cellId: 'boss-box-8', value: 8, isArmored: true },
        { cellId: 'boss-box-10', value: 10, requiresActivationCellId: 'gray-10-1' },
      ],
    },
  },
};
