import { DungeonMapDefinition } from '../types';

export const PUZZLED_PYRAMID_MAP: DungeonMapDefinition = {
  id: 'puzzled-pyramid',
  name: 'Puzzled Pyramid',
  difficulty: 'Intermediate',
  startCellIds: ['start-4', 'start-7', 'start-10'],
  cells: {
    'start-4': {
      id: 'start-4',
      type: 'START',
      label: '4',
      value: 4,
      row: 0,
      col: 0,
      connectedCellIds: ['reg-3-1', 'chest-1'],
    },
    'start-7': {
      id: 'start-7',
      type: 'START',
      label: '7',
      value: 7,
      row: 2,
      col: 0,
      connectedCellIds: ['reg-6-1', 'gray-7-1', 'reg-8-1'],
    },
    'start-10': {
      id: 'start-10',
      type: 'START',
      label: '10',
      value: 10,
      row: 4,
      col: 0,
      connectedCellIds: ['reg-11-1', 'chest-2'],
    },

    'chest-1': {
      id: 'chest-1',
      type: 'CHEST',
      label: 'Chest (+3 Black Dice)',
      row: 0,
      col: 1,
      connectedCellIds: ['start-4', 'm1-box-5'],
      chestReward: 'BLACK_DICE',
    },
    'chest-2': {
      id: 'chest-2',
      type: 'CHEST',
      label: 'Chest (+1 Torch)',
      row: 4,
      col: 1,
      connectedCellIds: ['start-10', 'm2-box-9'],
      chestReward: 'TORCH',
    },

    'reg-3-1': {
      id: 'reg-3-1',
      type: 'REGULAR',
      label: '3',
      value: 3,
      row: 1,
      col: 1,
      connectedCellIds: ['start-4', 'm1-box-5'],
    },
    'reg-6-1': {
      id: 'reg-6-1',
      type: 'REGULAR',
      label: '6',
      value: 6,
      row: 2,
      col: 1,
      connectedCellIds: ['start-7', 'gray-7-1'],
    },
    'gray-7-1': {
      id: 'gray-7-1',
      type: 'GRAY_ACTIVATION',
      label: '7 (Gray)',
      value: 7,
      row: 2,
      col: 2,
      connectedCellIds: ['reg-6-1', 'm1-box-6'],
    },
    'reg-8-1': {
      id: 'reg-8-1',
      type: 'REGULAR',
      label: '8',
      value: 8,
      row: 3,
      col: 1,
      connectedCellIds: ['start-7', 'gray-9-1'],
    },
    'gray-9-1': {
      id: 'gray-9-1',
      type: 'GRAY_ACTIVATION',
      label: '9 (Gray)',
      value: 9,
      row: 3,
      col: 2,
      connectedCellIds: ['reg-8-1', 'boss-box-9'],
    },
    'reg-11-1': {
      id: 'reg-11-1',
      type: 'REGULAR',
      label: '11',
      value: 11,
      row: 4,
      col: 2,
      connectedCellIds: ['start-10', 'm2-box-9'],
    },

    // Mummy Guard
    'm1-box-5': {
      id: 'm1-box-5',
      type: 'MONSTER',
      label: 'Mummy: 5',
      value: 5,
      row: 0,
      col: 3,
      monsterId: 'mummy',
      connectedCellIds: ['chest-1', 'reg-3-1', 'm1-box-6'],
    },
    'm1-box-6': {
      id: 'm1-box-6',
      type: 'MONSTER',
      label: 'Mummy: 6 (Req Gray 7)',
      value: 6,
      row: 1,
      col: 3,
      monsterId: 'mummy',
      requiresActivationCellId: 'gray-7-1',
      connectedCellIds: ['m1-box-5', 'gray-7-1'],
    },

    // Scarab Swarm
    'm2-box-9': {
      id: 'm2-box-9',
      type: 'MONSTER',
      label: 'Scarab: 9',
      value: 9,
      row: 4,
      col: 3,
      monsterId: 'scarab',
      connectedCellIds: ['chest-2', 'reg-11-1', 'm2-box-10'],
    },
    'm2-box-10': {
      id: 'm2-box-10',
      type: 'MONSTER',
      label: 'Scarab: 10',
      value: 10,
      row: 4,
      col: 4,
      monsterId: 'scarab',
      connectedCellIds: ['m2-box-9'],
    },

    // Sphinx Pharaoh (Boss)
    'boss-box-7': {
      id: 'boss-box-7',
      type: 'MONSTER',
      label: 'Pharaoh: 7',
      value: 7,
      row: 2,
      col: 4,
      monsterId: 'pharaoh',
      connectedCellIds: ['boss-box-9'],
    },
    'boss-box-9': {
      id: 'boss-box-9',
      type: 'MONSTER',
      label: 'Pharaoh: 9 (Req Gray 9)',
      value: 9,
      row: 3,
      col: 4,
      monsterId: 'pharaoh',
      requiresActivationCellId: 'gray-9-1',
      connectedCellIds: ['gray-9-1', 'boss-box-7', 'boss-box-11'],
    },
    'boss-box-11': {
      id: 'boss-box-11',
      type: 'MONSTER',
      label: 'Pharaoh: 11',
      value: 11,
      row: 3,
      col: 5,
      monsterId: 'pharaoh',
      connectedCellIds: ['boss-box-9'],
    },
  },
  monsters: {
    mummy: {
      id: 'mummy',
      name: 'Mummy Guard',
      isBoss: false,
      rewardGems: 3,
      lifePenaltyOnDefeat: 1,
      lifeBoxes: [
        { cellId: 'm1-box-5', value: 5 },
        { cellId: 'm1-box-6', value: 6, requiresActivationCellId: 'gray-7-1' },
      ],
    },
    scarab: {
      id: 'scarab',
      name: 'Scarab Swarm',
      isBoss: false,
      rewardGems: 3,
      lifePenaltyOnDefeat: 1,
      lifeBoxes: [
        { cellId: 'm2-box-9', value: 9 },
        { cellId: 'm2-box-10', value: 10 },
      ],
    },
    pharaoh: {
      id: 'pharaoh',
      name: 'Sphinx Pharaoh',
      isBoss: true,
      rewardGems: 6,
      lifePenaltyOnDefeat: 2,
      lifeBoxes: [
        { cellId: 'boss-box-7', value: 7 },
        { cellId: 'boss-box-9', value: 9, requiresActivationCellId: 'gray-9-1' },
        { cellId: 'boss-box-11', value: 11 },
      ],
    },
  },
};
